---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - ls
  when:
    event: pull_request

- name: github-comment
  image: jmccann/drone-github-comment:1
  when:
    event: pull_request
  message: Hello World!
  api_key: 8373ab1e79e5f54955a5d1c8c232b38d8638da42
