---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - npm i
  - npm run test
  when:
    event: pull_request

- name: github-comment
  image: jmccann/drone-github-comment:1
  when:
    event: pull_request
  message: Hello World!
