---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - npm i
  - npm test
  when:
    event: pull_request

trigger:
  event:
    - pull_request
  branch:
    - master